/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1

/NP/seedWithUUID

/NP/setTargetLength @TARGETLENGTH@
/NP/setTargetRadius @TARGETRADIUS@
/NP/setTargetMaterial @TARGETMATERIAL@

/NP/setReferencePhysList @PHYSICSLIST@
/physics_engine/tailor/MuonNuclear @NEWMUNUCLEARFLAG@

/NP/setFileName @ROOTFILENAME@

/run/initialize

/gps/particle mu+
/gps/energy @MUENERGY@
/gps/direction 0 0 1
/gps/position 0 0 -5 m

/run/beamOn @NEVENTS@

